# This workflow builds & runs test cases in iceoryx

name: Build, Test and get Test-Coverage 

# Triggers the workflow on push or pull request events but only for the master branch
on:
  push:
    # Any push event
    branches:
      - '**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This job builds & runs iceoryx tests in ubuntu-18.04
  build-test-ubuntu:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Install iceoryx dependencies
        # Softwares installed in ubuntu-18.04 instance 
        # https://github.com/actions/virtual-environments/blob/master/images/linux/Ubuntu1804-README.md
        run: sudo apt-get update && sudo apt-get install -y libacl1-dev libncurses5-dev git cmake build-essential lcov gcovr

      - name : Checkout
        uses: actions/checkout@v2
 
      - name: Build sources
        run: |
          export NUM_CORES=`nproc`
          # add flag to include coverage
          $GITHUB_WORKSPACE/tools/iceoryx_build_test.sh build-test with-dds-gateway clean strict -j $NUM_CORES coverage

      - name: Run tests
        run: |
          cd $GITHUB_WORKSPACE/build
          ../tools/run_all_tests.sh

      - name: coverage report by lcov, gcovr
        run: |
          cd $GITHUB_WORKSPACE
          lcov --capture --directory . -o lcov.info
          cd $GITHUB_WORKSPACE/build
          gcovr -r .. --xml >> coverage.xml
          cd $GITHUB_WORKSPACE

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./build/coverage.xml
          token: ed710fe8-1ffa-4683-9756-6319806183a2 # not required for public repos	

